const { Worker, Queue } = require("bullmq");
const { uploadToStorage } = require("../services/supabase.services");
const { Telegram } = require("telegraf");


const bot = new Telegram(process.env.TELEGRAM_BOT_TOKEN);

interface GlmResponse {
    choices: [
        {
            message: {
                content: string;
            }
        }
    ]
}

interface GlmError {
    error: {
        code: string;
        message: string;
    }
}

interface Job {
    data: {
        prompt: string;
        chatId: string;
    }
}

const connection = {
    host: "localhost",
    port: 6379
};

const codeQueue = new Queue("code", connection);

const worker = new Worker("prompt", async (job: Job) => {
    console.log(job.data);
    try {
        const response = await fetch("https://api.z.ai/api/paas/v4/chat/completions", {
            method: "POST",
            headers: {
                "Authorization": `Bearer ${process.env.GLM_API_KEY}`,
                "Content-Type": "application/json"
            },
            body: JSON.stringify({
                "model": "glm-4.7-flash",
                "messages": [
                    {
                        "role": "system",
                        "content": `You are a embedded programmer. You have to generate ESP32 code in espressif IDF compatible in .c extension. You have to just generate the code only no explanation needed. One thing if your are asked to fetch something from internet, don't write code for that you should fetch that data on your own and simply write code for displaying that value. If you need to setup OLED display, strictly follow below example - 
                        #include <driver/gpio.h>
                        #include <driver/i2c_master.h>
                        #include <esp_log.h>
                        #include <freertos/FreeRTOS.h>
                        #include <freertos/task.h>
                        #include <stdio.h>
                        #include <string.h>
                        #include "sdkconfig.h" // Don't miss .h extension

                        #include <u8g2.h>
                        #include "u8g2_esp32_hal.h"

                        // SDA - GPIO21
                        #define PIN_SDA 21

                        // SCL - GPIO22
                        #define PIN_SCL 22

                        static const char* TAG = "sh1106";

                        void app_main(void) {
                        u8g2_esp32_hal_t u8g2_esp32_hal = U8G2_ESP32_HAL_DEFAULT;
                        u8g2_esp32_hal.bus.i2c.sda = PIN_SDA;
                        u8g2_esp32_hal.bus.i2c.scl = PIN_SCL;
                        u8g2_esp32_hal_init(u8g2_esp32_hal);

                        u8g2_t u8g2;  // this structure which will contain all the data for the display
                            u8g2_Setup_sh1106_i2c_128x64_noname_f(&u8g2, U8G2_R0,
                            u8g2_esp32_i2c_byte_cb,
                            u8g2_esp32_gpio_and_delay_cb);  // These are I2C callback function for mapping 


                        u8x8_SetI2CAddress(&u8g2.u8x8, 0x78);  // The address is left-shifted 1 bit
                        ESP_LOGI(TAG, "u8g2_InitDisplay");
                        u8g2_InitDisplay(&u8g2);  // send init sequence to the display, display is in sleep mode after this,

                        ESP_LOGI(TAG, "u8g2_SetPowerSave");
                        u8g2_SetPowerSave(&u8g2, 0);  // wake up display
                        ESP_LOGI(TAG, "u8g2_ClearBuffer");
                        u8g2_ClearBuffer(&u8g2);

                        u8g2_SetFont(&u8g2 ,u8g2_font_helvR08_tr);
                        u8g2_DrawButtonUTF8(&u8g2, 64, 50, U8G2_BTN_SHADOW1|U8G2_BTN_HCENTER|U8G2_BTN_BW2, 56,  2,  2, "Subscribe to ltkdt" );
                        
                        u8g2_SendBuffer(&u8g2); // Send the buffer data to display
                        u8g2_DrawStr(&u8g2, 2, 17, "Hi nkolban!");
                        vTaskDelete(NULL);
                        }
                        `
                    },
                    {
                        "role": "user",
                        "content": `${job.data.prompt}`
                    }
                ]
            })
        });

        const data = (await response.json()) as GlmResponse | GlmError;

        if ((data as GlmError).error) {
            console.log("Error: ", (data as GlmError).error.message);
            return;
        }

        let code = (data as GlmResponse).choices[0].message.content;

        console.log("Code generated by GLM: ", code);

        code = code.replace("```c", "").replace("```", "").trim();

        const fileName = `codes/${job.data.chatId}_${Date.now()}.c`;

        await bot.sendMessage(job.data.chatId, "Code generated successfully");

        await uploadToStorage({
            fileName: fileName,
            fileBuffer: Buffer.from(code)
        });

        await codeQueue.add("code", {
            link: fileName,
            chatId: job.data.chatId
        });

        console.log("Code uploaded to storage");
    } catch (error) {
        console.log("Error in worker: ", error);
    }

}, {
    connection
});

